FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci

ARG NODE_ENV
ARG MONGO_PROD_DB
ARG ADMIN_EMAIL
ARG ADMIN_PASS
ARG COORDINATOR_EMAIL
ARG COORDINATOR_PASS
ARG REGISTER_FRONTEND_URL
ARG REGISTER_ORG_FRONTEND_URL
ARG FRONTEND_LINK

ENV MONGO_PROD_DB=$MONGO_PROD_DB
ENV NODE_ENV=$NODE_ENV
ENV ADMIN_EMAIL=$ADMIN_EMAIL
ENV ADMIN_PASS=$ADMIN_PASS
ENV COORDINATOR_EMAIL=$COORDINATOR_EMAIL
ENV COORDINATOR_PASS=$COORDINATOR_PASS
ENV REGISTER_FRONTEND_URL=$REGISTER_FRONTEND_URL
ENV REGISTER_ORG_FRONTEND_URL=$REGISTER_ORG_FRONTEND_URL
ENV FRONTEND_LINK=$FRONTEND_LINK

COPY . .
RUN npm run build
RUN npm run seed
RUN npm prune --production
EXPOSE 4000
CMD ["node", "dist/index.js"]
